Ta load capability
firscity/zephyr-optee-client pull request #1
Opened 2023-06-30 07:38 UTC by dsemenets

2023-06-30 08:47 UTC, oleksiimoisieiev requested changes

2023-06-30 08:47 UTC, oleksiimoisieiev commented on tee_supplicant/CMakeLists.txt
> +zephyr_include_directories(../public)
please remove extra line

2023-06-30 08:47 UTC, oleksiimoisieiev commented on tee_supplicant/include/teec_ta_load.h
> + * Copyright (c) 2014, STMicroelectronics International N.V.
Are you sure it's correct Copyright?

2023-06-30 08:47 UTC, oleksiimoisieiev commented on tee_supplicant/include/teec_ta_load.h
> +void TEEC_SetTATable(struct ta_table *table);
This requires comment as it is in LoadSecureModule

2023-06-30 08:47 UTC, oleksiimoisieiev commented on tee_supplicant/src/tee_supplicant.c
> +	int fd;
why do you need fd here?

2023-06-30 08:47 UTC, oleksiimoisieiev commented on tee_supplicant/src/tee_supplicant.c
> +		return -1;
Please return at least errno on error

2023-06-30 08:47 UTC, oleksiimoisieiev commented on tee_supplicant/src/tee_supplicant.c
> +//		LOG_ERR("terminating...");
please no comments

2023-06-30 08:47 UTC, oleksiimoisieiev commented on tee_supplicant/src/tee_supplicant.c
> +//		LOG_ERR("terminating...");
please no comments

2023-06-30 08:47 UTC, oleksiimoisieiev commented on tee_supplicant/src/teec_ta_load.c
> + * Copyright (c) 2014, STMicroelectronics International N.V.
copyright?

2023-06-30 08:47 UTC, oleksiimoisieiev commented on tee_supplicant/CMakeLists.txt
> +zephyr_library_sources(src/teec_ta_load.c)
Commit descrition

2023-06-30 08:47 UTC, oleksiimoisieiev commented on tee_supplicant/src/teec_ta_load.c
> +	ta_table = table;
if (table != NULL)?

2023-06-30 08:47 UTC, oleksiimoisieiev commented on tee_supplicant/src/teec_ta_load.c
> +		if (!strcmp(uuid, t->uuid)) {
please prefer using strncmp

2023-06-30 08:47 UTC, oleksiimoisieiev commented on tee_supplicant/src/teec_ta_load.c
> +	if (!ta || !ta_table)
|| !ta_size

2023-06-30 08:47 UTC, oleksiimoisieiev requested changes

2023-06-30 08:47 UTC, oleksiimoisieiev commented on tee_supplicant/src/tee_supplicant.c
>  	LOG_ERR("Receiving request...");
Please try to avoid this commit

2023-07-03 09:20 UTC, dsemenets commented on tee_supplicant/CMakeLists.txt
> +zephyr_include_directories(../public)
This line is not my change

2023-07-03 09:20 UTC, dsemenets commented on tee_supplicant/src/tee_supplicant.c
> +	int fd;
removed

2023-07-03 09:20 UTC, dsemenets commented on tee_supplicant/src/tee_supplicant.c
> +//		LOG_ERR("terminating...");
Done

2023-07-03 09:20 UTC, dsemenets commented on tee_supplicant/src/tee_supplicant.c
> +//		LOG_ERR("terminating...");
Done

2023-07-03 09:20 UTC, dsemenets commented on tee_supplicant/src/teec_ta_load.c
> + * Copyright (c) 2014, STMicroelectronics International N.V.
Fixed

2023-07-03 09:20 UTC, dsemenets commented on tee_supplicant/src/teec_ta_load.c
> +	ta_table = table;
Why?

2023-07-03 09:20 UTC, dsemenets commented on tee_supplicant/src/teec_ta_load.c
> +	if (!ta || !ta_table)
Fixed

2023-07-03 09:20 UTC, dsemenets commented on tee_supplicant/src/teec_ta_load.c
> +		if (!strcmp(uuid, t->uuid)) {
Ok

2023-07-03 09:20 UTC, dsemenets commented on tee_supplicant/src/tee_supplicant.c
> +		return -1;
Ok

2023-07-03 09:20 UTC, dsemenets commented on tee_supplicant/src/tee_supplicant.c
>  	LOG_ERR("Receiving request...");
Actually it is not my change but Ok

2023-07-03 09:20 UTC, dsemenets commented on tee_supplicant/include/teec_ta_load.h
> +void TEEC_SetTATable(struct ta_table *table);
Done

2023-07-03 09:20 UTC, dsemenets commented on tee_supplicant/include/teec_ta_load.h
> + * Copyright (c) 2014, STMicroelectronics International N.V.
Corrected

2023-07-03 09:46 UTC, oleksiimoisieiev approved these changes

2023-07-03 09:46 UTC, oleksiimoisieiev commented on tee_supplicant/include/teec_ta_load.h
> +void TEEC_SetTATable(struct ta_table *table);
+

2023-07-03 09:46 UTC, oleksiimoisieiev commented on tee_supplicant/src/teec_ta_load.c
> +	ta_table = table;
+

2023-07-03 09:48 UTC, oleksiimoisieiev commented
Add commit message and +1 
Acked-by: Oleksii Moisieiev <oleksii_moisieiev@epam.com>

2023-07-14 14:11 UTC, closed without merging